default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: scout_db_development

production:
  <<: *default
  database: scout_db_production

test:
  <<: *default
  database: scout_db_testing
